[package]
name = "ed-derive"
version = "0.1.1"
authors = ["Matt Bell <mappum@gmail.com>"]
edition = "2018"
description = "Derive macros for the ed crate"
license = "MIT"

[lib]
proc-macro = true

[dependencies]
syn = "1.0.17"
proc-macro2 = "1.0.10"
quote = "1.0.3"
